#index:
#    path: /
#    controller: App\Controller\DefaultController::index
   
homepage_translation:
    path: /{_locale}
    controller: App\Controller\DefaultController::homepage
    defaults:
        _locale: en 
    requirements:
        _locale: 'en|pt'
        
add_product:
    path: /{_locale}/add/product 
    controller: App\Controller\ProductController::addProduct
    requirements:
        _locale: 'en|pt'
    
product_display:
    path: /{_locale}/products
    controller: App\Controller\ProductController::displayProducts
    requirements:
        _locale: 'en|pt'

product:
    path: /{_locale}/product/{product}
    controller: App\Controller\ProductController::displayProduct
    defaults:
        _locale: en
    requirements:
        _locale: 'en|pt'
        product: '^[0-9]+$'

register:
    path: /{_locale}/register
    controller: App\Controller\UserController::register
    requirements:
        _locale: 'en|pt'
    
user_activate:
    path: /{_locale}/user/activate/{token}
    controller: App\Controller\UserController::activateUser
    requirements:
        _locale: 'en|pt'
        tokens: '[a-z0-9-]+'
        
username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']
    
login:
    path: /{_locale}/login
    controller: App\Controller\UserController::login
    
logout:
    path: /logout
    